# Generated by Django 3.0.5 on 2020-11-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_usergroups_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroups',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='applications',
            name='businessCriticality',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='functionalFit',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='hostingTypeTag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='leadingBusinessCapability',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='lifecycle_active',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='lifecycle_endOfLife',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='lifecycle_plan',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='majorInformationSystemsTag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='successors',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='technicalFit',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='timeTag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='applications',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='businessValue',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='lifecycleCustom_approved',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='lifecycleCustom_cancelled',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='lifecycleCustom_planningStarted',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='lifecycleCustom_projectedCompletion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='lifecycleCustom_projectedStart',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='projectRisk',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='projectStatus',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
